"""empty message

Revision ID: 257a38199f43
Revises: c0020df3631e
Create Date: 2025-08-11 00:49:30.796929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257a38199f43'
down_revision = 'c0020df3631e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_vehicles_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'])
        batch_op.drop_column('vehicles_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicles_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_vehicles_id_fkey', 'vehicle', ['vehicles_id'], ['id'])
        batch_op.drop_column('vehicle_id')

    # ### end Alembic commands ###
